services:
  db:
    image: postgres
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - 8080:8080
    container_name: adminer
    restart: always
    depends_on:
      db:
        condition: service_healthy

  api:
    build: ./creation_api
    ports:
      - 4000:4000
    command: npm run seed
    restart: always
    env_file: .env
    volumes:
      - ./creation_api:/app/
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ./frontend-github-repos
    command: npm run dev
    restart: always
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=http://localhost:4000
    volumes:
      - ./frontend-github-repos:/app/

  gateway:
    image: nginx
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - client
